# -*- coding: utf-8 -*-
# Auto-generated by ScreenForge AI Agent
import allure

from common.logs import log

@allure.feature('Core Business Flow')
@allure.story('inputs_form')
def test_inputs_form(d):
    """inputs_form

    Replay auto-recorded UI steps. For Web, param d is the Playwright page object."""
    with allure.step('Navigate to: [https://the-internet.herokuapp.com/inputs]'):
        log.info('Action: navigate to [https://the-internet.herokuapp.com/inputs]')
        d.goto('https://the-internet.herokuapp.com/inputs', wait_until='load')
    with allure.step('Input: [42] into [input[type=number]]'):
        log.info('Action: input [42] into [input[type=number]]')
        d.locator('input[type=number]').first.fill('42', timeout=30000.0)
    with allure.step('Assert: element [input[type=number]] exists'):
        log.info('Assert: check element [input[type=number]] exists')
        import playwright.sync_api
        try:
            d.locator('input[type=number]').first.wait_for(state='visible', timeout=30000.0)
            is_exist = True
        except playwright.sync_api.TimeoutError:
            is_exist = False
        if not is_exist:
            log.error('Assertion failed: element [input[type=number]] not found')
        assert is_exist, 'Assertion failed: element input[type=number] not found'
        log.info('Assertion passed: element exists')
