# -*- coding: utf-8 -*-
# Auto-generated by ScreenForge AI Agent
import allure

from common.logs import log

@allure.feature('Core Business Flow')
@allure.story('checkboxes')
def test_checkboxes(d):
    """checkboxes

    Replay auto-recorded UI steps. For Web, param d is the Playwright page object."""
    with allure.step('Navigate to: [https://the-internet.herokuapp.com/checkboxes]'):
        log.info('Action: navigate to [https://the-internet.herokuapp.com/checkboxes]')
        d.goto('https://the-internet.herokuapp.com/checkboxes', wait_until='load')
    with allure.step('Click: [#checkboxes input:first-child]'):
        log.info('Action: click [#checkboxes input:first-child]')
        d.locator('#checkboxes input:first-child').first.click(timeout=30000.0)
    with allure.step('Assert: element [#checkboxes] exists'):
        log.info('Assert: check element [#checkboxes] exists')
        import playwright.sync_api
        try:
            d.locator('#checkboxes').first.wait_for(state='visible', timeout=30000.0)
            is_exist = True
        except playwright.sync_api.TimeoutError:
            is_exist = False
        if not is_exist:
            log.error('Assertion failed: element [#checkboxes] not found')
        assert is_exist, 'Assertion failed: element #checkboxes not found'
        log.info('Assertion passed: element exists')
